Add option to show folders first in the sidebar
srid/emanote pull request #399
Opened 2022-12-22 19:15 UTC by jfpedroza

Solves https://github.com/EmaApps/emanote/discussions/164. Requires https://github.com/srid/heist-extra/pull/2. I'll update `flake.nix` once it is merged.

2022-12-23 00:55 UTC, srid commented on src/Emanote/View/Template.hs
> +            Meta.lookupRouteMeta @Bool False ("template" :| ["sidebar", "folders-first"]) tr model
You want to update `default/index.yaml` to add this new key.

2022-12-24 03:09 UTC, srid commented
bors try

2022-12-27 15:43 UTC, srid commented
https://github.com/srid/heist-extra/pull/2 's merged now.

2023-01-02 04:15 UTC, srid requested changes
@jfpedroza I don't think I have rights to push to your branch. Please re-open your PR, and merge from `master` branch.

2023-01-15 04:10 UTC, jfpedroza commented
Hey @srid, just updated from master. 

"Allow edits by maintainers" was checked. I unchecked it and checked it again. Let me know if you still can't modify and I'll re-open the PR.

2023-03-18 22:47 UTC, srid commented
bors try

2023-08-20 00:51 UTC, merged